### ISSUE TITLE
Some Pictures and more explanation of Minestamp please <3

### ISSUE THREAD

**Issue by ryantheleach** [Nlkomaru/MineStamp#56]
konichiwa,

On https://minestamp.nikomaru.page/ it talks about generating keypairs, what is the purpose of this? is it necessary to use S3 in order to use MineStamp?

Also I would love to see some pictures or videos of Minestamp in action.

<3

**Comment by Nlkomaru** [comment]
original: key pairを生成する理由については、プレイヤーごとに絵文字を与えるためのチケット（絵文字チケット）にデータを書き込む際に、json web tokenを使用しており、その整合性チェックのために使用しているためです。
また、単一のサーバーのみで使用する際s3は必要ありません。複数のサーバーで共有したいときのみ利用できます。

translated: The reason for generating key pairs is that json web tokens are used to write data in tickets for giving emoji to each player (emoji tickets), and are used to check the integrity of the tickets.
Also, s3 is not required when using only a single server. You can use it only when you want to share it with multiple servers.

**Comment by Nlkomaru** [comment]
picture: https://modrinth.com/plugin/minestamp/gallery

video: 

https://github.com/user-attachments/assets/53124092-2dfc-4fe9-9ea2-6cdfc40487ea
